"""initial database schema

Revision ID: 5e44dcb47019
Revises:
Create Date: 2026-08-14 18:54:42.919252

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e44dcb47019"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=True),
        sa.Column("entity_id", sa.String(length=128), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_audit_events_user_id"), "audit_events", ["user_id"], unique=False)
    op.create_table(
        "broker_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("broker_type", sa.String(length=50), nullable=False),
        sa.Column("account_mode", sa.String(length=20), nullable=False),
        sa.Column("secret_ref", sa.String(length=255), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_broker_connections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_connections")),
    )
    op.create_index(
        op.f("ix_broker_connections_account_mode"),
        "broker_connections",
        ["account_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_broker_connections_broker_type"),
        "broker_connections",
        ["broker_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_broker_connections_user_id"), "broker_connections", ["user_id"], unique=False
    )
    op.create_table(
        "risk_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("risk_per_trade_pct", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("daily_loss_limit_pct", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("max_open_positions", sa.Integer(), nullable=False),
        sa.Column("max_total_exposure_pct", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_risk_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_profiles")),
    )
    op.create_index(op.f("ix_risk_profiles_user_id"), "risk_profiles", ["user_id"], unique=False)
    op.create_table(
        "trading_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("broker_connection_id", sa.String(length=36), nullable=False),
        sa.Column("broker_account_id", sa.String(length=128), nullable=False),
        sa.Column("server", sa.String(length=255), nullable=True),
        sa.Column("currency", sa.String(length=16), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_connection_id"],
            ["broker_connections.id"],
            name=op.f("fk_trading_accounts_broker_connection_id_broker_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trading_accounts")),
        sa.UniqueConstraint(
            "broker_connection_id",
            "broker_account_id",
            name="uq_trading_accounts_connection_account",
        ),
    )
    op.create_index(
        op.f("ix_trading_accounts_broker_connection_id"),
        "trading_accounts",
        ["broker_connection_id"],
        unique=False,
    )
    op.create_table(
        "execution_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("broker_connection_id", sa.String(length=36), nullable=False),
        sa.Column("trading_account_id", sa.String(length=36), nullable=True),
        sa.Column("client_order_id", sa.String(length=128), nullable=False),
        sa.Column("broker_order_id", sa.String(length=128), nullable=True),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("side", sa.String(length=20), nullable=False),
        sa.Column("order_type", sa.String(length=30), nullable=False),
        sa.Column("requested_quantity", sa.Numeric(precision=24, scale=10), nullable=False),
        sa.Column("approved_quantity", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("risk_snapshot_json", sa.Text(), nullable=False),
        sa.Column("request_snapshot_json", sa.Text(), nullable=False),
        sa.Column("broker_response_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_connection_id"],
            ["broker_connections.id"],
            name=op.f("fk_execution_records_broker_connection_id_broker_connections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trading_account_id"],
            ["trading_accounts.id"],
            name=op.f("fk_execution_records_trading_account_id_trading_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_execution_records_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_records")),
    )
    op.create_index(
        op.f("ix_execution_records_broker_connection_id"),
        "execution_records",
        ["broker_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_records_broker_order_id"),
        "execution_records",
        ["broker_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_records_client_order_id"),
        "execution_records",
        ["client_order_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_execution_records_status"), "execution_records", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_execution_records_symbol"), "execution_records", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_execution_records_trading_account_id"),
        "execution_records",
        ["trading_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_records_user_id"), "execution_records", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_execution_records_user_id"), table_name="execution_records")
    op.drop_index(op.f("ix_execution_records_trading_account_id"), table_name="execution_records")
    op.drop_index(op.f("ix_execution_records_symbol"), table_name="execution_records")
    op.drop_index(op.f("ix_execution_records_status"), table_name="execution_records")
    op.drop_index(op.f("ix_execution_records_client_order_id"), table_name="execution_records")
    op.drop_index(op.f("ix_execution_records_broker_order_id"), table_name="execution_records")
    op.drop_index(op.f("ix_execution_records_broker_connection_id"), table_name="execution_records")
    op.drop_table("execution_records")
    op.drop_index(op.f("ix_trading_accounts_broker_connection_id"), table_name="trading_accounts")
    op.drop_table("trading_accounts")
    op.drop_index(op.f("ix_risk_profiles_user_id"), table_name="risk_profiles")
    op.drop_table("risk_profiles")
    op.drop_index(op.f("ix_broker_connections_user_id"), table_name="broker_connections")
    op.drop_index(op.f("ix_broker_connections_broker_type"), table_name="broker_connections")
    op.drop_index(op.f("ix_broker_connections_account_mode"), table_name="broker_connections")
    op.drop_table("broker_connections")
    op.drop_index(op.f("ix_audit_events_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
